#!/bin/bash
#
# --- SSH Security Hardening Script ---
#
# 功能:
# 1. 将指定的公钥添加到当前用户的 authorized_keys 文件中。
# 2. 修改 SSHD 配置文件，禁用密码登录，并确保公钥登录已启用。
# 3. 重启 SSH 服务使配置生效。
#
# 使用方法:
# 1. 将此脚本保存为 setup_ssh.sh 文件。
# 2. 上传到您的目标服务器。
# 3. 授予执行权限: chmod +x setup_ssh.sh
# 4. 使用 sudo 执行: sudo ./setup_ssh.sh

# --- 配置区 ---
# 将您的公钥粘贴到这里
# IMPORTANT: This is the public key to be added.
readonly PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICtm9SaEUaLDqC0gsDrRYQOV+eFtGi+Beu4Fl+3Agff9 Generated By Termius"

# --- 脚本主体 ---

# 如果任何命令失败，立即退出
set -e

echo "--- SSH 安全加固脚本开始执行 ---"

# --- 步骤 1: 添加公钥 ---
# 获取运行此脚本的用户的家目录，即使使用了sudo
if [ "$SUDO_USER" ]; then
    TARGET_USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    TARGET_USER_HOME="$HOME"
fi

AUTH_KEYS_FILE="$TARGET_USER_HOME/.ssh/authorized_keys"

echo "INFO: 准备将公钥添加到 $AUTH_KEYS_FILE..."

# 创建 .ssh 目录和 authorized_keys 文件 (如果不存在)
mkdir -p "$(dirname "$AUTH_KEYS_FILE")"
chmod 700 "$(dirname "$AUTH_KEYS_FILE")"
touch "$AUTH_KEYS_FILE"
chmod 600 "$AUTH_KEYS_FILE"

# 检查公钥是否已存在，避免重复添加
if grep -q -F "$PUBKEY" "$AUTH_KEYS_FILE"; then
    echo "INFO: 公钥已存在于 $AUTH_KEYS_FILE 文件中，跳过添加。"
else
    echo "$PUBKEY" >> "$AUTH_KEYS_FILE"
    echo "SUCCESS: 公钥已成功添加。"
fi

# 确保文件所有权正确
if [ "$SUDO_USER" ]; then
    chown -R "$SUDO_USER:$SUDO_USER" "$(dirname "$AUTH_KEYS_FILE")"
    echo "INFO: 已将 $TARGET_USER_HOME/.ssh 目录的所有权设置为 $SUDO_USER."
fi


# --- 步骤 2: 修改 SSHD 配置文件 ---
SSHD_CONFIG_FILE="/etc/ssh/sshd_config"

echo "INFO: 正在修改 $SSHD_CONFIG_FILE..."

# 使用 sed 安全地修改配置，这会处理已存在或被注释的行
# 确保公钥认证开启
sed -i -E 's/^[#\s]*PubkeyAuthentication\s+.*/PubkeyAuthentication yes/' "$SSHD_CONFIG_FILE"
echo " -> 已设置 'PubkeyAuthentication yes'"

# 禁用密码认证
sed -i -E 's/^[#\s]*PasswordAuthentication\s+.*/PasswordAuthentication no/' "$SSHD_CONFIG_FILE"
echo " -> 已设置 'PasswordAuthentication no'"

# (可选但推荐) 禁用基于密码的质询响应认证
sed -i -E 's/^[#\s]*ChallengeResponseAuthentication\s+.*/ChallengeResponseAuthentication no/' "$SSHD_CONFIG_FILE"
echo " -> 已设置 'ChallengeResponseAuthentication no'"

echo "SUCCESS: SSH 配置文件修改完成。"


# --- 步骤 3: 重启 SSH 服务 ---
echo "INFO: 正在尝试重启 SSH 服务以应用更改..."

# 尝试多种方式重启，以兼容不同系统 (systemd vs init.d)
if command -v systemctl &> /dev/null && systemctl list-units --type=service | grep -q 'sshd.service'; then
    systemctl restart sshd.service
    echo "SUCCESS: sshd.service 服务已重启。"
elif command -v systemctl &> /dev/null && systemctl list-units --type=service | grep -q 'ssh.service'; then
    systemctl restart ssh.service
    echo "SUCCESS: ssh.service 服务已重启。"
elif command -v service &> /dev/null; then
    service ssh restart || service sshd restart
    echo "SUCCESS: SSH 服务已通过 'service' 命令重启。"
else
    echo "WARNING: 无法自动重启 SSH 服务。请手动重启 (例如: 'sudo systemctl restart ssh' 或 '/etc/init.d/ssh restart')." >&2
fi

echo ""
echo "✅ --- 配置完成 ---"
echo "🔴 警告：在断开当前连接之前，请务必打开一个新的终端窗口，测试您的密钥登录是否成功，以防被锁定！"
echo "🔴 WARNING: Before you close this session, open a NEW terminal and test your key-based login."

exit 0
